# Numpy Primer

In [6]:
import numpy as np

#  1-D

## (Generate) Some Data

In [7]:
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

countries.size

20

In [8]:
?np.arange

In [ ]:
np.arange?

In [9]:
values = np.arange(1,countries.size,2)
values

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
values = np.arange(countries.size)
values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.linspace?

In [13]:
values = np.linspace(0,95,countries.size)
values

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95.])

## Basic Operations

In [14]:
# Accessing elements
print(countries[0])
print(countries[3])

Afghanistan
Angola


In [15]:
# Slicing
print(countries[0:3])
print(countries[:3])
print(countries[17:])
print(countries[:])

['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


In [16]:
# Element types
print(countries.dtype)
print(values.dtype)
print(np.array([0, 1, 2, 3]).dtype)
print(np.array([1.0, 1.5, 2.0, 2.5]).dtype)
print(np.array([True, False, True]).dtype)
print(np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)

<U22
float64
int64
float64
bool
<U2


In [18]:
# Looping 1
for country in countries:
    #print('Country {}'.format(country))
    print('Country %s' % country)

Country Afghanistan
Country Albania
Country Algeria
Country Angola
Country Argentina
Country Armenia
Country Australia
Country Austria
Country Azerbaijan
Country Bahamas
Country Bahrain
Country Bangladesh
Country Barbados
Country Belarus
Country Belgium
Country Belize
Country Benin
Country Bhutan
Country Bolivia
Country Bosnia and Herzegovina


In [19]:
# Looping 2
for i in range(len(countries)):
    country = countries[i]
    print('Country {} -> {}'.format(country,
            values[i]))

Country Afghanistan -> 0.0
Country Albania -> 5.0
Country Algeria -> 10.0
Country Angola -> 15.0
Country Argentina -> 20.0
Country Armenia -> 25.0
Country Australia -> 30.0
Country Austria -> 35.0
Country Azerbaijan -> 40.0
Country Bahamas -> 45.0
Country Bahrain -> 50.0
Country Bangladesh -> 55.0
Country Barbados -> 60.0
Country Belarus -> 65.0
Country Belgium -> 70.0
Country Belize -> 75.0
Country Benin -> 80.0
Country Bhutan -> 85.0
Country Bolivia -> 90.0
Country Bosnia and Herzegovina -> 95.0


In [21]:
# Looping 3
for i, country in enumerate(countries):
    print('Country {} -> {}'.format(country,
            i))

Country Afghanistan -> 0
Country Albania -> 1
Country Algeria -> 2
Country Angola -> 3
Country Argentina -> 4
Country Armenia -> 5
Country Australia -> 6
Country Austria -> 7
Country Azerbaijan -> 8
Country Bahamas -> 9
Country Bahrain -> 10
Country Bangladesh -> 11
Country Barbados -> 12
Country Belarus -> 13
Country Belgium -> 14
Country Belize -> 15
Country Benin -> 16
Country Bhutan -> 17
Country Bolivia -> 18
Country Bosnia and Herzegovina -> 19


## Statistic Functions

In [ ]:
print(values.mean())
print(values.std())
print(values.max())
print(values.sum())

In [24]:
i=values.argmax()
(countries[i],values[i])

('Bosnia and Herzegovina', 95.0)

In [25]:
i=values.argmin()
(countries[i],values[i])

('Afghanistan', 0.0)

## Index Arrays

In [26]:
a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, False])

print(a[b])

[1 2]


In [27]:
print(a[np.array([True, False, True, False])])

[1 3]


In [31]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 2, 1])

print(b == 2)
print(a[b == 2])

[False  True False  True False]
[2 4]


In [35]:
# values/countries, where value>20
print(values[values>20])
print(countries[values>20])

[ 25.  30.  35.  40.  45.  50.  55.  60.  65.  70.  75.  80.  85.  90.  95.]
['Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina']


In [37]:
# values/countries, where value>20 and value<80
print(values[(values>20) & (values<80)])
print(countries[(values>20) & (values<80)])

[ 25.  30.  35.  40.  45.  50.  55.  60.  65.  70.  75.]
['Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize']


In [38]:
# sum of all values, where value>20 and value<80
print(values[(values>20) & (values<80)].sum())

550.0


In [39]:
# also sum of all values, where value>20 and value<80
# (see bool algebra: A & B == not(notA | notB))
print(values[~((values<=20) | (values>=80))].sum())

550.0


# 2-D

In [ ]:
values_1d=np.arange(0,50)
print("1-D: {}".format(values_1d))
values_2d = values_1d.reshape(10,5)
values_2d

In [ ]:
# Accessing elements
print (values_2d[1, 3])
print (values_2d[1:3, 3:5])
print (values_2d[1, :])

In [ ]:
# Vectorized operations on rows or columns
print (values_2d[0, :] + values_2d[1, :])
print (values_2d[:, 0] + values_2d[:, 1])

In [ ]:
# Vectorized operations on entire arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
a + b

In [ ]:
np.sum?

In [ ]:
# NumPy axis argument
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print (a.sum())
print (a.sum(axis=0)) # along 'row'
print (a.sum(axis=1)) # along 'column'